### ISSUE TITLE
Inconsistent usage of "web page" vs "webpage"

### ISSUE THREAD

**Issue by vtbassmatt** [vtbassmatt/simplewebpage#1]
Decide whether you want to say "web page" or "webpage". It's used both ways across index.html, the readme, and the project title.

**Comment by dogert** [comment]
Which do you prefer?  Web page or webpage?  I'm fine with either, but agree on the need for consistency.

**Comment by vtbassmatt** [comment]
I'm no documentation expert but let's go with "webpage".
